core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("DashboardAdmin.urls")),
    path('user/',include("DashboardUser.urls")),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='Registration/password_reset_form.html'), name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(template_name='Registration/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='Registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='Registration/password_reset_complete.html'), name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

DashboardAdmin/models.py
from datetime import datetime
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.dispatch import receiver
import os

class Cargo(models.Model):
    nombre = models.CharField(max_length=500)

    def __str__(self):
        return self.nombre

class Empleado(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    edad = models.IntegerField(validators=[MaxValueValidator(100), MinValueValidator(18)], null=True, blank=True)
    correo = models.EmailField(max_length=254, blank=True, null=True)
    telefono = models.CharField(max_length=10)
    fecha_inicio = models.DateField(null=True, blank=True)
    fecha_nac = models.DateField(null=True, blank=True)
    picture = models.ImageField(upload_to='usuarios/perfiles/', null=True, blank=True)
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE, null=True, blank=True)
    departamento = models.CharField(max_length=100, null=True, blank=True)
    DNI = models.CharField(max_length=8, null=True, blank=True)
    active = models.BooleanField(default=True)
    alias = models.CharField(max_length=100, null=True, blank=True)
    frase = models.CharField(max_length=100, null=True, blank=True)
    fondo = models.ImageField(upload_to='usuarios/fondos/', null=True, blank=True)
    
    def save(self, *args, **kwargs):
        try:
            this = Empleado.objects.get(id=self.id)
            if this.picture != self.picture and this.fondo != self.fondo:
                this.picture.delete(save=False)
                this.fondo.delete(save=False)
        except: pass 
        super().save(*args, **kwargs)

    def __str__(self):
        return '{} {}'.format(self.nombre, self.apellido)
    
@receiver(models.signals.post_delete, sender=Empleado)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.picture:
        if os.path.isfile(instance.picture.path):
            os.remove(instance.picture.path)
    
    

class Venta(models.Model):
    nombre = models.CharField(max_length=150)
    date_joined = models.DateField(default=datetime.now)
    monto = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return str(self.nombre)
    

class CategoriaRecurso(models.Model):
    nombre = models.CharField(max_length=150)
    descripcion = models.TextField()
    
    def __str__(self):
        return str(self.nombre)
    
class Recurso(models.Model):
    nombre = models.CharField(max_length=150)
    descripcion = models.TextField()
    date_joined = models.DateField(auto_now_add=True)
    categoria = models.ForeignKey(CategoriaRecurso, on_delete=models.CASCADE)
    link = models.URLField(max_length=200, null=True, blank=True)
    documento = models.FileField(upload_to='documents/', null=True, blank=True)
    background = models.ImageField(upload_to='images/', null=True, blank=True)
    
    def __str__(self):
        return str(self.nombre)
    
    def save(self, *args, **kwargs):
        try:
            this = Recurso.objects.get(id=self.id)
            if this.documento != self.documento:
                this.documento.delete(save=False)
        except: pass 
        super().save(*args, **kwargs)
        
@receiver(models.signals.post_delete, sender=Recurso)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.documento:
        if os.path.isfile(instance.documento.path):
            os.remove(instance.documento.path)
            


class CategoriaInventario(models.Model):
    nombre = models.CharField(max_length=150)
    descripcion = models.TextField()
    
    def __str__(self):
        return str(self.nombre)   

class Sucursal(models.Model):
    nombre = models.CharField(max_length=150)
    logo = models.ImageField(upload_to='logos/', null=True, blank=True)
    
    def __str__(self):
        return str(self.nombre)
    
    def save(self, *args, **kwargs):
        try:
            this = Sucursal.objects.get(id=self.id)
            if this.logo != self.logo:
                this.logo.delete(save=False)
        except: pass 
        super().save(*args, **kwargs)
        

class Local(models.Model):
    ubicacion = models.CharField(max_length=150)
    nombre = models.CharField(max_length=150)
    telefono = models.CharField(max_length=10)
    empresa = models.ForeignKey(Sucursal, on_delete=models.CASCADE)
    encargado = models.ForeignKey(Empleado, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.nombre)
    
    
class Producto(models.Model):
    nombre = models.CharField(max_length=150)
    date_joined = models.DateField(auto_now_add=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    picture = models.ImageField(upload_to='productos/', null=True, blank=True)
    categoria = models.ForeignKey(CategoriaInventario, on_delete=models.CASCADE)
    sucursal = models.ForeignKey(Sucursal, on_delete=models.CASCADE, related_name='productos')
    local = models.ForeignKey(Local, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.nombre)
    
    def save(self, *args, **kwargs):
        try:
            this = Producto.objects.get(id=self.id)
            if this.picture != self.picture:
                this.picture.delete(save=False)
        except: pass 
        super().save(*args, **kwargs)
        
@receiver(models.signals.post_delete, sender=Producto)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.picture:
        if os.path.isfile(instance.picture.path):
            os.remove(instance.picture.path)


class Categoria_Informe(models.Model):
    nombre = models.CharField(max_length=250)
    
    def __str__(self):
        return self.nombre
            
class Informe(models.Model):
    resumen = models.CharField(max_length=250)
    documento = models.FileField(upload_to='informes/', null=True, blank=True)
    categoria = models.ForeignKey(Categoria_Informe, on_delete=models.CASCADE)
    fecha_subida = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.resumen
            
    def save(self, *args, **kwargs):
        try:
            this = Informe.objects.get(id=self.id)
            if this.documento != self.documento:
                this.documento.delete(save=False)
        except: pass 
        super().save(*args, **kwargs)
        
@receiver(models.signals.post_delete, sender=Informe)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.documento:
        if os.path.isfile(instance.documento.path):
            os.remove(instance.documento.path)
            
class RegistroEntrada(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    fecha = models.DateTimeField(auto_now_add=True)
    hora_ingreso = models.TimeField(auto_now_add=True)
    encargado = models.ForeignKey(Empleado, on_delete=models.CASCADE)

    def __str__(self):
        return f'Entrada de {self.producto.nombre} ({self.cantidad})'
    
class RegistroSalida(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    fecha = models.DateTimeField(auto_now_add=True)
    hora_salida = models.TimeField(auto_now_add=True)
    encargado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    motivo = models.TextField()
    ganacias = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return f'Salida de {self.producto.nombre} ({self.cantidad})'
    
class Notificacion(models.Model):
    mensaje = models.CharField(max_length=500, blank=True, null=True)
    imagen = models.ImageField(upload_to='notificaciones/', null=True, blank=True)
    creado_por = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.mensaje

templates/User/resources/Home.html
{% extends "base.html" %}
{% load static %}
{% block estilos %}
<style>
    .swiper-wrapper {
        width: 350px;
        height: 350px;
    }
    .swiper-slide {
        margin-right: 20px;
    }
</style>
{% endblock estilos %}
{% block navegacion %}
    {% include "src/components/navbar.html" %}
    {% include "User/components/aside.html" %}
{% endblock navegacion %}
{% block content %}
<section class="overflow-y-scroll bg-gray-200 pb-20 ml-64 p-4 h-full" id="ContentDashboard" >
    {% include "Recursos/Form.html" %}
    {% include "Recursos/Form2.html" %}
    {% include "Recursos/Description.html" %}
    {% if user.is_superuser %}
    <div class="flex gap-4 pl-3 mb-5 ">
        <button id="OpenFormCategoria" class="align-middle select-none flex items-center gap-3 mt-3  text-center uppercase transition-all text-xs py-1 px-3 rounded-lg border border-gray-400  focus:ring focus:ring-gray-300 active:opacity-[0.85]" type="button" style="position: relative; overflow: hidden;">
            <i class='bx bx-purchase-tag-alt text-xl text-blue-900'></i>
            Agregar Categoria
        </button>
        <button id="OpenFormCategoria2" class="align-middle select-none flex items-center gap-3 mt-3  text-center uppercase transition-all text-xs py-1 px-3 rounded-lg border border-gray-400  focus:ring focus:ring-gray-300 active:opacity-[0.85]" type="button" style="position: relative; overflow: hidden;">
            <i class='bx bx-file text-xl text-blue-900'></i>
            Agregar Recurso
        </button>
    </div>
    {% else %}
    {% endif %}
        {% if sourcecat %}
        <div class="swiper mySwiper">
            {% for category in sourcecat %}
                    <div class="p-2">
                        <h2 class="text-2xl font-bold text-gray-800">
                            {{ category.nombre }}
                        </h2>
                        <p class=" text-gray-600">
                            Se encontraron {{ category.recurso_set.all.count }} recursos en esta categoría
                        </p>
                    </div>
                    <div class="swiper-wrapper" id="{{category.nombre}}" >
                        {% if category.recurso_set.all %}
                            {% for recurso in category.recurso_set.all %}
                            <div class="swiper-slide">
                                <article class="relative group isolate flex flex-col justify-end mb-8 overflow-hidden rounded-2xl px-8 pb-8 pt-36 max-w-sm mt-6 transition-transform transform duration-500">
                                    {% if recurso.background %}
                                        <img src="{{recurso.background.url}}"" alt="{{ recurso.nombre }}" class="absolute inset-0 h-full w-full object-cover group-hover:scale-110 duration-500 transition-all">
                                    {% else %}
                                        <img src="https://images.unsplash.com/photo-1499856871958-5b9627545d1a" alt="{{ recurso.nombre }}" class="absolute inset-0 h-full w-full object-cover group-hover:scale-110 duration-500 transition-all">
                                    {% endif %}
                                    <div class="absolute inset-0 bg-gradient-to-t from-gray-900 via-gray-900/40"></div>
                                        <h3 class="z-10 mt-3 text-2xl font-bold text-white">
                                            {{ recurso.nombre }}
                                        </h3>
                                        <div class="z-10 gap-y-1 h-12 flex justify-between items-center overflow-hidden text-sm leading-6 text-gray-300">
                                            <p class="text-sm">
                                                {{ recurso.date_joined }}
                                            </p>
                                            <div class="flex items-center gap-3">
                                                {% if recurso.link %}
                                                <a href="{{ recurso.link }}" target="_blank">
                                                    <i class='bx bx-link text-2xl'></i>
                                                </a>
                                                {% else %}
                                                {% endif %}
                                                {% if recurso.documento %}
                                                <a href="{{recurso.documento.url }}" download>
                                                    <i class='bx bxs-download text-2xl'></i>
                                                </a>
                                                {% else %}
                                                {% endif %}
                                                {% if recurso.descripcion %}
                                                <a id="OpenDescription{{ forloop.counter }}" class="open-description" href="javascript:void(0);" data-description="{{ recurso.descripcion }}">
                                                    <i class='bx bx-info-circle text-2xl'></i>
                                                </a>
                                                {% else %}
                                                {% endif %}
                                            </div>
                                        </div>
                                </article>
                            </div>
                            {% endfor %}
                        {% else %}
                            <span class="font-thin">
                                No hay recursos en esta categoria
                            </span>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            {% else %}  
            <span class="text-2xl">
                No hay categorias
            </span>
            {% endif %}
        </div>
</section>
{% endblock content %}
{% block script %}
<script>
    // modal de descripción
    document.querySelectorAll('.open-description').forEach(function(element) {
        element.addEventListener('click', function() {
            const description = this.getAttribute('data-description');
            const modal = document.getElementById('ModalDescription');
            modal.querySelector('#modal-description-content').textContent = description;
            modal.classList.remove('hidden');
        });
    });

    // cerrar el modal
    document.getElementById('CloseDescription').addEventListener('click', function() {
        document.getElementById('ModalDescription').classList.add('hidden');
    });
</script>
{% endblock script %}